=== api-evangelist/amazon-mq/json-schema/mq-api-create-broker-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-mq/refs/heads/main/json-schema/mq-api-create-broker-request-schema.json",
  "title": "CreateBrokerRequest",
  "description": "Creates a broker using the specified properties.",
  "type": "object",
  "properties": {
    "AuthenticationStrategy": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AuthenticationStrategy"
        },
        {
          "xml": {
            "name": "authenticationStrategy"
          },
          "description": "Optional. The authentication strategy used to secure the broker. The default is SIMPLE."
        }
      ]
    },
    "AutoMinorVersionUpgrade": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__boolean"
        },
        {
          "xml": {
            "name": "autoMinorVersionUpgrade"
          },
          "description": "Enables automatic upgrades to new minor versions for brokers, as new versions are released and supported by Amazon MQ. Automatic upgrades occur during the scheduled maintenance window of the broker or after a manual broker reboot. Set to true by default, if no value is specified."
        }
      ]
    },
    "BrokerName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "xml": {
            "name": "brokerName"
          },
          "description": "Required. The broker's name. This value must be unique in your AWS account, 1-50 characters long, must contain only letters, numbers, dashes, and underscores, and must not contain white spaces, brackets, wildcard characters, or special characters."
        }
      ]
    },
    "Configuration": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ConfigurationId"
        },
        {
          "xml": {
            "name": "configuration"
          },
          "description": "A list of information about the configuration."
        }
      ]
    },
    "CreatorRequestId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "xml": {
            "name": "creatorRequestId"
          },
          "description": "The unique ID that the requester receives for the created broker. Amazon MQ passes your ID with the API action. Note: We recommend using a Universally Unique Identifier (UUID) for the creatorRequestId. You may omit the creatorRequestId if your application doesn't require idempotency."
        }
      ]
    },
    "DeploymentMode": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DeploymentMode"
        },
        {
          "xml": {
            "name": "deploymentMode"
          },
          "description": "Required. The broker's deployment mode."
        }
      ]
    },
    "EncryptionOptions": {
      "allOf": [
        {
          "$ref": "#/components/schemas/EncryptionOptions"
        },
        {
          "xml": {
            "name": "encryptionOptions"
          },
          "description": "Encryption options for the broker. Does not apply to RabbitMQ brokers."
        }
      ]
    },
    "EngineType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/EngineType"
        },
        {
          "xml": {
            "name": "engineType"
          },
          "description": "Required. The type of broker engine. Currently, Amazon MQ supports ACTIVEMQ and RABBITMQ."
        }
      ]
    },
    "EngineVersion": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "xml": {
            "name": "engineVersion"
          },
          "description": "Required. The broker engine's version. For a list of supported engine versions, see <a href=\"https://docs.aws.amazon.com//amazon-mq/latest/developer-guide/broker-engine.html\">Supported engines</a>."
        }
      ]
    },
    "HostInstanceType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "xml": {
            "name": "hostInstanceType"
          },
          "description": "Required. The broker's instance type."
        }
      ]
    },
    "LdapServerMetadata": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LdapServerMetadataInput"
        },
        {
          "xml": {
            "name": "ldapServerMetadata"
          },
          "description": "Optional. The metadata of the LDAP server used to authenticate and authorize connections to the broker. Does not apply to RabbitMQ brokers."
        }
      ]
    },
    "Logs": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Logs"
        },
        {
          "xml": {
            "name": "logs"
          },
          "description": "Enables Amazon CloudWatch logging for brokers."
        }
      ]
    },
    "MaintenanceWindowStartTime": {
      "allOf": [
        {
          "$ref": "#/components/schemas/WeeklyStartTime"
        },
        {
          "xml": {
            "name": "maintenanceWindowStartTime"
          },
          "description": "The parameters that determine the WeeklyStartTime."
        }
      ]
    },
    "PubliclyAccessible": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__boolean"
        },
        {
          "xml": {
            "name": "publiclyAccessible"
          },
          "description": "Enables connections from applications outside of the VPC that hosts the broker's subnets. Set to false by default, if no value is provided."
        }
      ]
    },
    "SecurityGroups": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__listOf__string"
        },
        {
          "xml": {
            "name": "securityGroups"
          },
          "description": "The list of rules (1 minimum, 125 maximum) that authorize connections to brokers."
        }
      ]
    },
    "StorageType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/BrokerStorageType"
        },
        {
          "xml": {
            "name": "storageType"
          },
          "description": "The broker's storage type."
        }
      ]
    },
    "SubnetIds": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__listOf__string"
        },
        {
          "xml": {
            "name": "subnetIds"
          },
          "description": "<p>The list of groups that define which subnets and IP ranges the broker can use from different Availability Zones. If you specify more than one subnet, the subnets must be in different Availability Zones. Amazon MQ will not be able to create VPC endpoints for your broker with multiple subnets in the same Availability Zone. A SINGLE_INSTANCE deployment requires one subnet (for example, the default subnet). An ACTIVE_STANDBY_MULTI_AZ Amazon MQ for ActiveMQ deployment requires two subnets. A CLUSTER_MULTI_AZ Amazon MQ for RabbitMQ deployment has no subnet requirements when deployed with public accessibility. Deployment without public accessibility requires at least one subnet.</p> <important><p>If you specify subnets in a <a href=\"https://docs.aws.amazon.com/vpc/latest/userguide/vpc-sharing.html\">shared VPC</a> for a RabbitMQ broker, the associated VPC to which the specified subnets belong must be owned by your AWS account. Amazon MQ will not be able to create VPC endpoints in VPCs that are not owned by your AWS account.</p></important>"
        }
      ]
    },
    "Tags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__mapOf__string"
        },
        {
          "xml": {
            "name": "tags"
          },
          "description": "Create tags when creating the broker."
        }
      ]
    },
    "Users": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__listOfUser"
        },
        {
          "xml": {
            "name": "users"
          },
          "description": "<p>Required. The list of broker users (persons or applications) who can access queues and topics. This value can contain only alphanumeric characters, dashes, periods, underscores, and tildes (- . _ ~). This value must be 2-100 characters long.</p> <important><title>Amazon MQ for RabbitMQ</title> <p>When you create an Amazon MQ for RabbitMQ broker, one and only one administrative user is accepted and created when a broker is first provisioned. All subsequent broker users are created by making RabbitMQ API calls directly to brokers or via the RabbitMQ web console.</p></important>"
        }
      ]
    }
  },
  "required": [
    "EngineVersion",
    "HostInstanceType",
    "AutoMinorVersionUpgrade",
    "Users",
    "BrokerName",
    "DeploymentMode",
    "EngineType",
    "PubliclyAccessible"
  ]
}

=== api-evangelist/amazon-mq/examples/mq-api-create-broker-request-example.json
{
  "AuthenticationStrategy": "example-value",
  "AutoMinorVersionUpgrade": "example-value",
  "BrokerName": "example-resource",
  "Configuration": "example-value",
  "CreatorRequestId": "id-abc123",
  "DeploymentMode": "example-value",
  "EncryptionOptions": "example-value",
  "EngineType": "STANDARD",
  "EngineVersion": "example-value",
  "HostInstanceType": "STANDARD",
  "LdapServerMetadata": "example-value",
  "Logs": "example-value",
  "MaintenanceWindowStartTime": "example-value",
  "PubliclyAccessible": "example-value",
  "SecurityGroups": "example-value",
  "StorageType": "STANDARD",
  "SubnetIds": "id-abc123",
  "Tags": "example-value",
  "Users": "example-value"
}
